In [12]:
from glob import glob
import pandas as pd
from datetime import datetime
import numpy as np

In [13]:
def countRiders(month, dataframe):
    d = {}
    df = dataframe.loc[dataframe['month'] == str(month)]
    d['Rider Total'] = len(df)
    d['Female Total'] = len(df.loc[df['gender'] == '2'])
    d['Male Total'] = len(df.loc[df['gender'] == '1'])
    d['Undisclosed Total'] = len(df.loc[df['gender'] == '0'])
    d['Annual Members'] = len(df.loc[df['usertype'] == 'Subscriber'])
    d['Non Members'] = len(df.loc[df['usertype'] == 'Customer'])

    return d

In [14]:
def ridersPerMonth(dataframe):
    i = 1
    x =1
    months = []
    
    while i < 13:
        data = countRiders(x, dataframe)
        months.append(data)
        i += 1
        x += 1
        
    return months

In [15]:
def bikeDataToDF(year):
    combined_csv = sorted(glob(f'data/{year}/*-citibike-tripdata.csv'))
    
    cbd_df = pd.concat((pd.read_csv(file).assign(filename = file)
          for file in combined_csv), ignore_index = True)
    
    cbd_df['starttime'] = pd.to_datetime(cbd_df['starttime'])
    cbd_df['stoptime'] = pd.to_datetime(cbd_df['stoptime'])
    cbd_df['year'] = cbd_df['starttime'].dt.year
    cbd_df['month'] = cbd_df['starttime'].dt.month
    cbd_df['day'] = cbd_df['starttime'].dt.day

    cbd_df['month'] = cbd_df['month'].astype(str)
    cbd_df['day'] = cbd_df['day'].astype(str)
    cbd_df['gender'] = cbd_df['gender'].astype(str)
    
    return cbd_df

In [16]:
def bikeDataToDataFrame(year):
    combined_csv = sorted(glob(f'data/{year}/*-citibike-tripdata.csv'))
    
    cbd_df = pd.concat((pd.read_csv(file).assign(filename = file)
          for file in combined_csv), ignore_index = True)
    
    cbd_df['starttime'] = pd.to_datetime(cbd_df['starttime'])
    cbd_df['stoptime'] = pd.to_datetime(cbd_df['stoptime'])
#     cbd_df['year'] = cbd_df['starttime'].dt.year
#     cbd_df['month'] = cbd_df['starttime'].dt.month
#     cbd_df['day'] = cbd_df['starttime'].dt.day

#     cbd_df['month'] = cbd_df['month'].astype(str)
#     cbd_df['day'] = cbd_df['day'].astype(str)
#     cbd_df['gender'] = cbd_df['gender'].astype(str)
    
    return cbd_df

In [17]:
def getYearlyRiderCount(year):
    df = pd.DataFrame(ridersPerMonth(bikeDataToDF(f'{year}')))
    df.insert(0, 'Year', f'{year}')
    df.insert(1, 'Month', range(1, 1 + len(df)))
    
    return df

In [ ]:
# 2020 Data
getYearlyRiderCount(2020).to_csv('data/output/2020_ridership.csv', index=False)

In [ ]:
# 2019 Data
getYearlyRiderCount(2019).to_csv('data/output/2019_ridership.csv', index=False)

In [ ]:
# 2018 Data
getYearlyRiderCount(2018).to_csv('data/output/2018_ridership.csv', index=False)

In [ ]:
# 2017 Data
getYearlyRiderCount(2017).to_csv('data/output/2017_ridership.csv', index=False)

In [ ]:
# 2016 Data
# getYearlyRiderCount(2016).to_csv('data/output/2016_ridership.csv', index=False)

In [ ]:
allData_csv = sorted(glob(f'data/output/*_ridership.csv'))
    
allData_df = pd.concat((pd.read_csv(file).assign(filename = file)
      for file in allData_csv), ignore_index = True)
allData_df

In [ ]:
allData_df.to_csv('data/output/citibike_ridership.csv', index=False)

In [18]:
data_2020 = bikeDataToDataFrame(2020)
data_2020['bike_usage'] = data_2020.groupby('bikeid')['bikeid'].transform('count')
data_2020['start_station_count'] = data_2020.groupby('start station id')['start station id'].transform('count')
data_2020['end_station_count'] = data_2020.groupby('end station id')['end station id'].transform('count')
data_2020.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,filename,bike_usage,start_station_count,end_station_count
0,789,2020-01-01 00:00:55.390,2020-01-01 00:14:05.147,504,1 Ave & E 16 St,40.732219,-73.981656,307,Canal St & Rutgers St,40.714275,-73.989900,30326,Subscriber,1992,1,data/2020\202001-citibike-tripdata.csv,1366,59142,52211
1,1541,2020-01-01 00:01:08.102,2020-01-01 00:26:49.178,3423,West Drive & Prospect Park West,40.661063,-73.979453,3300,Prospect Park West & 8 St,40.665147,-73.976376,17105,Customer,1969,1,data/2020\202001-citibike-tripdata.csv,764,48873,16094
2,1464,2020-01-01 00:01:42.140,2020-01-01 00:26:07.011,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,-74.012342,40177,Subscriber,1963,1,data/2020\202001-citibike-tripdata.csv,1745,73560,31685
3,592,2020-01-01 00:01:45.561,2020-01-01 00:11:38.155,346,Bank St & Hudson St,40.736529,-74.006180,490,8 Ave & W 33 St,40.751551,-73.993934,27690,Subscriber,1980,1,data/2020\202001-citibike-tripdata.csv,1022,38629,62776
4,702,2020-01-01 00:01:45.788,2020-01-01 00:13:28.240,372,Franklin Ave & Myrtle Ave,40.694546,-73.958014,3637,Fulton St & Waverly Ave,40.683239,-73.965996,32583,Subscriber,1982,1,data/2020\202001-citibike-tripdata.csv,776,8071,16257

In [19]:
start = data_2020.groupby('start station id')['start station id'].transform('count')
stop = data_2020.groupby('end station id')['end station id'].transform('count')
data_2020['total_usage'] = start + stop
data_2020.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,filename,bike_usage,start_station_count,end_station_count,total_usage
0,789,2020-01-01 00:00:55.390,2020-01-01 00:14:05.147,504,1 Ave & E 16 St,40.732219,-73.981656,307,Canal St & Rutgers St,40.714275,-73.989900,30326,Subscriber,1992,1,data/2020\202001-citibike-tripdata.csv,1366,59142,52211,111353
1,1541,2020-01-01 00:01:08.102,2020-01-01 00:26:49.178,3423,West Drive & Prospect Park West,40.661063,-73.979453,3300,Prospect Park West & 8 St,40.665147,-73.976376,17105,Customer,1969,1,data/2020\202001-citibike-tripdata.csv,764,48873,16094,64967
2,1464,2020-01-01 00:01:42.140,2020-01-01 00:26:07.011,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,-74.012342,40177,Subscriber,1963,1,data/2020\202001-citibike-tripdata.csv,1745,73560,31685,105245
3,592,2020-01-01 00:01:45.561,2020-01-01 00:11:38.155,346,Bank St & Hudson St,40.736529,-74.006180,490,8 Ave & W 33 St,40.751551,-73.993934,27690,Subscriber,1980,1,data/2020\202001-citibike-tripdata.csv,1022,38629,62776,101405
4,702,2020-01-01 00:01:45.788,2020-01-01 00:13:28.240,372,Franklin Ave & Myrtle Ave,40.694546,-73.958014,3637,Fulton St & Waverly Ave,40.683239,-73.965996,32583,Subscriber,1982,1,data/2020\202001-citibike-tripdata.csv,776,8071,16257,24328

In [20]:
data_2020['total_trip_duration_(mins)'] = data_2020.groupby('bikeid')['tripduration'].transform('sum')
data_2020['total_trip_duration_(mins)'] = data_2020['total_trip_duration_(mins)'].div(60).round(2) 
data_2020.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,...,bikeid,usertype,birth year,gender,filename,bike_usage,start_station_count,end_station_count,total_usage,total_trip_duration_(mins)
0,789,2020-01-01 00:00:55.390,2020-01-01 00:14:05.147,504,1 Ave & E 16 St,40.732219,-73.981656,307,Canal St & Rutgers St,40.714275,...,30326,Subscriber,1992,1,data/2020\202001-citibike-tripdata.csv,1366,59142,52211,111353,22109.95
1,1541,2020-01-01 00:01:08.102,2020-01-01 00:26:49.178,3423,West Drive & Prospect Park West,40.661063,-73.979453,3300,Prospect Park West & 8 St,40.665147,...,17105,Customer,1969,1,data/2020\202001-citibike-tripdata.csv,764,48873,16094,64967,15117.53
2,1464,2020-01-01 00:01:42.140,2020-01-01 00:26:07.011,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,...,40177,Subscriber,1963,1,data/2020\202001-citibike-tripdata.csv,1745,73560,31685,105245,30998.93
3,592,2020-01-01 00:01:45.561,2020-01-01 00:11:38.155,346,Bank St & Hudson St,40.736529,-74.006180,490,8 Ave & W 33 St,40.751551,...,27690,Subscriber,1980,1,data/2020\202001-citibike-tripdata.csv,1022,38629,62776,101405,16776.67
4,702,2020-01-01 00:01:45.788,2020-01-01 00:13:28.240,372,Franklin Ave & Myrtle Ave,40.694546,-73.958014,3637,Fulton St & Waverly Ave,40.683239,...,32583,Subscriber,1982,1,data/2020\202001-citibike-tripdata.csv,776,8071,16257,24328,15612.07

In [ ]:
np.sort(data_2020['bikeid'].unique())[::-1]

In [ ]:
len(data_2020['bikeid'].unique())

In [ ]:
test = data_2020['bikeid'].value_counts().nlargest(1000)
test

In [21]:
filtered_data_2020 = data_2020.loc[data_2020['bike_usage'] > 1668]
filtered_data_2020

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,...,bikeid,usertype,birth year,gender,filename,bike_usage,start_station_count,end_station_count,total_usage,total_trip_duration_(mins)
2,1464,2020-01-01 00:01:42.140,2020-01-01 00:26:07.011,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,...,40177,Subscriber,1963,1,data/2020\202001-citibike-tripdata.csv,1745,73560,31685,105245,30998.93
21,1222,2020-01-01 00:06:56.397,2020-01-01 00:27:18.528,513,W 56 St & 10 Ave,40.768254,-73.988639,3244,University Pl & E 8 St,40.731437,...,34396,Subscriber,1981,1,data/2020\202001-citibike-tripdata.csv,1669,32390,46539,78929,30578.63
24,1364,2020-01-01 00:07:34.025,2020-01-01 00:30:18.241,513,W 56 St & 10 Ave,40.768254,-73.988639,3233,E 48 St & 5 Ave,40.757246,...,39065,Subscriber,1981,1,data/2020\202001-citibike-tripdata.csv,1715,32390,32243,64633,29251.55
38,1211,2020-01-01 00:09:54.740,2020-01-01 00:30:06.247,3160,Central Park West & W 76 St,40.778968,-73.973747,3671,E 81 St & 2 Ave,40.774779,...,38797,Subscriber,1971,1,data/2020\202001-citibike-tripdata.csv,1774,35249,26563,61812,31169.10
39,2637,2020-01-01 00:10:02.875,2020-01-01 00:54:00.669,3349,Grand Army Plaza & Plaza St West,40.672968,-73.970880,157,Henry St & Atlantic Ave,40.690893,...,39345,Subscriber,1989,1,data/2020\202001-citibike-tripdata.csv,1878,40286,18649,58935,35729.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19506775,1185,2020-12-31 23:47:03.689,2021-01-01 00:06:48.801,495,W 47 St & 10 Ave,40.762699,-73.993012,495,W 47 St & 10 Ave,40.762699,...,38612,Subscriber,1958,1,data/2020\202012-citibike-tripdata.csv,1705,50489,50015,100504,30386.47
19506785,1025,2020-12-31 23:48:27.168,2021-01-01 00:05:32.709,281,Grand Army Plaza & Central Park S,40.764397,-73.973715,3671,E 81 St & 2 Ave,40.774779,...,42019,Subscriber,1971,1,data/2020\202012-citibike-tripdata.csv,1701,51290,26563,77853,30454.30
19506816,1074,2020-12-31 23:52:32.057,2021-01-01 00:10:26.312,448,W 37 St & 10 Ave,40.756604,-73.997901,447,8 Ave & W 52 St,40.763707,...,41947,Subscriber,1963,1,data/2020\202012-citibike-tripdata.csv,1692,47159,58543,105702,37693.57
19506838,76,2020-12-31 23:56:20.484,2020-12-31 23:57:37.234,312,Allen St & Stanton St,40.722055,-73.989111,265,Stanton St & Chrystie St,40.722293,...,40896,Subscriber,1994,2,data/2020\202012-citibike-tripdata.csv,1929,47053,38443,85496,34358.47
19506852,2045,2020-12-31 23:58:21.704,2021-01-01 00:32:27.157,526,E 33 St & 5 Ave,40.747659,-73.984907,3614,Crescent St & 30 Ave,40.768692,...,36467,Subscriber,1994,1,data/2020\202012-citibike-tripdata.csv,1734,38555,8890,47445,56445.43

In [22]:
filtered_data_2020.to_csv('data/output/2020_topbikes.csv', index=False)